#
# LoginMessages v3.0
#
# There are two sections: ranks and players
# The ranks are permission based. Some example ranks are already created, but you can
# change these to your likings. Use %player% to display their name when they log in.
#
# Example:
# SuperAdmin:
#   permission: loginmessages.superadmin
#   message: "<aqua>%player% is a <italic>Super Admin"
#
# The player section is designed for a player to have their own login message.
# This is not permission based, but rather username based. Use %player% to display their name when they log in.
# Note that if a user has a player login message, they will not be able to use the ranks
# Example:
# Madgeek1450:
#   message: "<aqua>%player% is a <gold>Master-ass-kicker<aqua>."
#
ranks:
  Moderator:
    permission: loginmessages.moderator
    message: "<aqua>%player% is a <purple><italic>Moderator"
  Admin:
    permission: loginmessages.admin
    message: "<aqua>%player% is an <dark_red><italic>Admin"
  Builder:
    permission: loginmessages.builder
    message: "<aqua>%player% is a <italic>Builder"
  Developer:
    permission: loginmessages.developer
    message: "<aqua>%player% is a <dark_purple><italic>Developer"
  Owner:
    permission: loginmessages.owner
    message: "<aqua>%player% is the <dark_red><italic>Owner"
players:
  Telesphoreo:
    message: "<aqua>The %player% it's in the?"
  OxLemonxO:
    message: "<aqua>%player% is the <dark_red>Ki<dark_purple>ng <gold>Of <dark_purple>Le<gold>mo<gray>ns<aqua>!"

# Should the vanilla "joined the game" message show?
show_vanilla_messages: false