#
# Login Messages v1.1.1
#
# There are two sections, ranks and players
# The ranks are permission based. Some example ranks are already created, but you can
# change these to your likings. Use %player% to display their name when they log in.
#
# Example:
# SuperAdmin:
#   permission: loginmessages.superadmin
#   message: "&b%player% is a &oSuper Admin"
#
# The player section is designed for a player to have their own login message.
# This is not permission based, but rather username based. Use %player% to display their name when they log in.
# Note that if a user has a player login message, they will not be able to use the ranks
# Example:
# Madgeek1450:
#   message: "&b%player% is a &6Master-ass-kicker&b."
#
ranks:
  Moderator:
    permission: loginmessages.moderator
    message: "&b%player% is a &d&oModerator"
  Admin:
    permission: loginmessages.admin
    message: "&b%player% is an &4&oAdmin"
  Builder:
    permission: loginmessages.builder
    message: "&b%player% is a &oBuilder"
  Developer:
    permission: loginmessages.developer
    message: "&b%player% is a &5&oDeveloper"
  Owner:
    permission: loginmessages.owner
    message: "&b%player% is the &4&oOwner"
players:
  handleDisconnect:
    message: "&b%player% is the &9&oCreator of LoginMessages"
  yashi4554:
    message: "&b%player% is an &4&oAdmin&b and the &9The Supreme Builder"
  OxLemonxO:
    message: "&b%player% is the &4Ki&5ng &6Of &5Le&6mo&7ns&b!"
# Should LoginMessages check for updates automatically?
enable_updater: 'true'