name: LoginMessages
version: 1.3.0
description: A simple, lightweight plugin to easily create login messages
author: Model_3
main: us.flowdesigns.loginmessages.LoginMessages
commands:
  loginmessages:
    usage: /<command> [reload | update]
    description: Shows information about, reload, or update LoginMessages