name: ${project.name}
version: ${project.version}
description: A simple, lightweight plugin to easily create login messages
author: Telesphoreo
main: me.telesphoreo.LoginMessages
api-version: 1.13
commands:
  loginmessages:
    usage: /<command> [reload]
    description: Shows information about or reload LoginMessages.
  setloginmessage:
    usage: /<command> <message>
    description: Set your login message in-game.
    aliases: [slm, setlogin]
  deleteloginmessage:
    usage: /<command>
    description: Delete your login message.
    aliases: [dlm, dellogin, deletelogin]